name: red_link
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Version info: [major].[minor].[patch]+[build]
version: 1.0.0+1

# Flutter SDK version required
environment:
  sdk: ^3.7.2

# Project dependencies (packages your app uses)
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8          # iOS-style icons
  http: any                        # HTTP requests
  firebase_core: any               # Required for using Firebase
  cloud_firestore: ^6.0.0          # Firebase Firestore (NoSQL DB)
  firebase_database: ^12.0.0       # Firebase Realtime Database
  firebase_auth: ^6.0.1            # Firebase Authentication
  url_launcher: ^6.3.1             # Open links in browser/apps
  lottie: ^3.3.1                   # JSON-based animations
  google_sign_in: ^6.2.1           # Google Sign-In
  flutter_facebook_auth: ^6.2.0    # Facebook Authentication
  font_awesome_flutter: ^10.7.0   

# Dev-only packages (used in development and testing)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0            # Recommended lint rules
  flutter_launcher_icons: ^0.14.3  # Auto-generate app launcher icons

# Flutter-specific settings
flutter:
  uses-material-design: true       # Enables Material icons

  assets:
    - assets/                      # Loads all files from assets folder

# Configuration for launcher icon generation
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/1024.png"